language: cpp
compiler: clang
os: linux
dist: xenial

#addons:
#  apt:
#    sources:
#      - ubuntu-toolchain-r-test
#    packages:
#      - g++-8

script:
#  - export CC=gcc-8
#  - export CXX=g++-8
  - mkdir build
  - cd build
  - cmake ..
  - make
